### ISSUE TITLE
command completeness checklist

### ISSUE THREAD

**Issue by mrparkerlol** [mrteenageparker/script-builder#4]
The following commands need to be added:

- [ ] create/scriptName
- [ ] createhttp/url or createh/url
- [ ] createsource/scriptName/source or creates/scriptName/source
- [ ] createhttpsource/scriptName/url, createhs/scriptName/url
- [ ] edith/scriptName/url
- [ ] edits/scriptName/source
- [x] insert, ins, i/assetid
- [x] local, x, l/source
- [ ] newlocal, nl/targets/source
- [x] script, s, c, do/source
- [ ] removesave, remsave, deletesave, delsave/scriptName
- [ ] remove, rem, delete, del/scriptName
- [ ] runlocal, rl/scriptName
- [x] httplocal, hl, rlh/url
- [x] httplocalto, hlt, rlth/targets/url
- [ ] rlt/targets/scriptName
- [ ] run, rs, r/scriptName
- [x] runh, rsh, rh, h/url
- [ ] save/scriptName
- [ ] share/targets/scriptName
- [ ] stop/scriptName

The following g/ commands need to be added

- [ ] ball, bl
- [x] base, bs, b
- [x] walls, wall, wl, w
- [ ] buildtools, btools, btool, bt
- [x] clean, cl, c
- [x] clearterrain, cleart
- [x] dummy, dum, d [/amount]
- [x] debug deb db
- [x] fixcamera, fixcam, fixc, fc
- [x] fixlighting, fixl
- [x] forcefield, ff
- [x] heal
- [x] help, h
- [x] join, j/playerName
- [x] jumppower, jp/number
- [x] nilcharacter, nilchar, nil
- [x] nowalls, nowall, nwl, nw
- [x] noforcefield, noff, nff
- [ ] noguis, nog, ng
- [x] nolocal, nol, nl
- [x] noscripts, nos, ns [/all]
- [x] noskies, nosky
- [x] noteams, noteam
- [x] notools, not, nt
- [ ] privateserver, ps/code
- [x] public, pub
- [x] r15, r6
- [x] rejoin, rj
- [x] reset, r
- [ ] scripts, s
- [x] supereset, sreset, sr
- [x] teleport, tp/playerName
- [x] walkspeed, ws/number
