### ISSUE TITLE
features/improvements checklist

### ISSUE THREAD

**Issue by mrparkerlol** [mrteenageparker/script-builder#5]
- [ ]  Modules are sandboxed (relies on backend)
- [ ]  game:GetObjects() added (instead of making incompatible changes to InsertService, relies on backend)
- [ ]  New UI and it's code (already have UI, just need to rework some code to support it)
- [ ]  Re-work ClientManager.client.lua (really needs a uplift/rewrite to be cleaner)
- [ ]  Support running unauthenticated in Studio (where locals work, but save scripts don't)
- [ ]  Work around more edge-cases involving nested script builders (sometimes using setmetatable on shared isn't possible, even in nested tables)
- [ ]  Support potentially sharing saved scripts between places, locked to userId (and the ability to toggle that off)
- [ ]  Add support for webhooks to create discord -> game chat communication for communities
- [ ]  Add text filtering to every instance that can display text in-game, created by code (sandbox)
- [ ]  Add text filtering to output, to prevent inappropriate output from being displayed.
- [ ]  Support running with HttpService disabled, but warn of the consequences
- [ ]  Add warnings for when LoadstringEnabled is false, to allow developers to handle it accordingly

**Comment by jLn0n** [comment]
[it has been near 3 years daddy](https://youtu.be/Sbw3sw7HKSQ)
